### ISSUE TITLE
Don't use __proto__

### ISSUE THREAD

**Issue by mishelashala** [vic/elmo#2]
`__proto__` is not an standard [feature](https://github.com/vic/elmo/blob/master/src/elmo/lens.js#L22). Actually is [deprecated](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/proto).

Instead use `Object.setPrototypeOf`. More info [here](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Object/setPrototypeOf).

**Comment by vic** [comment]
Hm, those places where I used `__proto__` are not for setting the prototype of an object, but that of a property descriptor. Dunno if it's also deprecated there, I used the example from [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

**Comment by vic** [comment]
Haha yeah, looks like it's `__proto__` is deprecated I'll remove it and be explicit instead

``` javascript
  enumerable: false,
  configurable: false,
  writable: false,
```
